# Generated by Django 3.1.3 on 2021-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210515_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='img/default-user-image.png', null=True, upload_to='profile/'),
        ),
    ]
