# Generated by Django 3.1.7 on 2021-04-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210430_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_liked',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
