# Generated by Django 3.1.3 on 2021-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
