# Generated by Django 3.1.7 on 2021-04-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210411_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/img/Default-user-image.png', null=True, upload_to='profile/'),
        ),
    ]
