# Generated by Django 3.1.3 on 2021-05-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210430_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-user-image.png', null=True, upload_to='profile/'),
        ),
    ]
