# Generated by Django 3.1.7 on 2021-05-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
