# Generated by Django 3.1.7 on 2021-05-09 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_liked',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
