# Generated by Django 3.1.7 on 2021-05-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
